# Generated by Django 4.2.14 on 2024-08-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_formsubmission_submission_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsubmission",
            name="submission_id",
        ),
    ]
