# Generated by Django 4.2.14 on 2024-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_publiccoupon_usercoupon_delete_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publiccoupon",
            old_name="discount",
            new_name="high_discount",
        ),
        migrations.RenameField(
            model_name="publiccoupon",
            old_name="minimum_purchase",
            new_name="high_minimum_purchase",
        ),
        migrations.AddField(
            model_name="publiccoupon",
            name="low_discount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publiccoupon",
            name="low_minimum_purchase",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publiccoupon",
            name="medium_discount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publiccoupon",
            name="medium_minimum_purchase",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
