# Generated by Django 4.2.14 on 2024-08-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_rename_discount_publiccoupon_high_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiccoupon",
            name="high_discount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publiccoupon",
            name="high_minimum_purchase",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publiccoupon",
            name="low_discount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publiccoupon",
            name="low_minimum_purchase",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publiccoupon",
            name="medium_discount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publiccoupon",
            name="medium_minimum_purchase",
            field=models.IntegerField(),
        ),
    ]
