# Generated by Django 4.2.14 on 2024-08-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
